echo "this is the first line of code"
echo "this is second line of code"
echo "this is the third line of code from DEV"
echo "This job is completed sucessfully" 
echo "Adding another line of code"
echo "Added sixth line"
echo "seventh line of code"
echo "eighth line of code"
echo "ninth line of code"
echo "tenth line of code"
